defaults:
  - _self_

system:
  CUDA_VISIBLE_DEVICES: "0"

micro_batch_size_per_gpu: 2
ppo_mini_batch_size: 8
model_path: Qwen/Qwen2.5-VL-3B-Instruct

actor_rollout_ref:
  model:
    path: ${model_path}
  actor:
    ppo_mini_batch_size: ${ppo_mini_batch_size}
    micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    ppo_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    use_ref: True
    entropy_coeff: 0.001
    kl_loss_coef: 0.001
    kl_loss_type: kl
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    optim:
      betas: [0.9, 0.999]
  ref:
    log_prob_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
  rollout:
    log_prob_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    tensor_model_parallel_size: 1
    max_model_len: 8192
    prompt_length: 1
    response_length: 256
    gpu_memory_utilization: 0.2
    max_num_batched_tokens: 2048
    temperature: 1
    rollout_filter_ratio: 0.25
    rollout_filter_type: std
    enforce_eager: True
    free_cache_engine: True
    disable_log_stats: True
    enable_chunked_prefill: False
    skip_tokenizer_init: False
    trust_remote_code: True  # Required for Qwen2.5-VL
    disable_mm_preprocessor_cache: True  # Important for vision models
    enable_prefix_caching: False
    # Vision model specific parameters
    limit_mm_per_prompt: {"image": 10, "video": 1}  # Allow multiple images per prompt
    val_kwargs:
      do_sample: False
      temperature: 0
      top_p: 1.0
      top_k: -1

data:
  max_prompt_length: null
  max_response_length: null
  train_batch_size: null

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  kl_penalty: kl
  use_kl_in_reward: True
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

agent_proxy:
  max_turn: 5
  action_sep: " | "
  max_actions_per_turn: 5
  use_turn_scores: False
  enable_think: True
  reward_normalization:
    grouping: "batch"
    method: "identity"

es_manager:
  format_penalty: -0.1
  train:
    env_groups: 1  # Total number of environment groups
    group_size: 2  # Environments per group
    env_configs:
      tags: ["SimpleSokoban"]
      n_groups: [1]  # Number of groups for each tag
  val:
    env_groups: 1  # Total number of environment groups for validation
    group_size: 1  # Environments per group (should be 1 for val due to temperature=0)
    env_configs:
      tags: ["SimpleSokoban"]
      n_groups: [1]  # Number of groups for each tag

custom_envs:
  SimpleSokoban:
    env_type: "sokoban"
    max_actions_per_traj: 10
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right | Right | Up</answer>."
    max_tokens: 128
    max_turn: 5
    env_config:
      dim_x: 6
      dim_y: 6
      num_boxes: 1
      max_steps: 100
      render_mode: "text"  # Default to text, will be changed to rgb_array in tests 