micro_batch_size_per_gpu: 4
ppo_mini_batch_size: 32
model_path: Qwen/Qwen2.5-VL-3B-Instruct

actor_rollout_ref:
  model:
    path: ${model_path}
  rollout:
    response_length: 256

agent_proxy:
  action_sep: " | "
  max_actions_per_turn: 5
  use_turn_scores: False
  enable_think: True
  reward_normalization:
    grouping: "batch"
    method: "identity"

es_manager:
  train:
    group_size: 2
    env_configs:
      tags: ["SimpleSokoban"]
      n_groups: [1]

custom_envs:
  SimpleSokoban:
    env_type: "sokoban"
    max_tokens: 128 