game_env:
  name: "ace_attorney"
  description: "Ace Attorney game environment using retro.Env and GymEnvAdapter."
  env_type: "retro"
  max_steps: 300
  seed: null
  num_runs: 1

agent:
  name: "ace_attorney_retro_agent"
  model_name: "gemini-2.5-flash-preview-04-17"
  cache_dir: "cache/retro_ace_attorney" 
  harness: true
  observation_mode: "both" # "vision", "text", or "both"
  use_reflection: true
  modules:
    base_module:
    
    perception_module: 

    memory_module:
      max_memory: 10
    
    reasoning_module:
      use_perception: True
      use_memory: True
      use_cot: True 