defaults:
  - base
  - _self_

# Support for multi-modal training: Override configurations for vision-based training

# Use the same vision model for both actor and critic (standard PPO approach)
model_path: Qwen/Qwen2.5-VL-3B-Instruct

# Smaller batch sizes for vision models to manage GPU memory
micro_batch_size_per_gpu: 1
ppo_mini_batch_size: 4

actor_rollout_ref:
  model:
    # Support for multi-modal training: Use vision model
    trust_remote_code: True
  rollout:
    # Support for multi-modal training: Vision-optimized vLLM settings
    gpu_memory_utilization: 0.8
    max_model_len: 4096
    trust_remote_code: True
    disable_mm_preprocessor_cache: True
    enable_chunked_prefill: False
    enable_prefix_caching: False
    limit_mm_per_prompt: {"image": 3, "video": 0}
    # Smaller batches for vision models
    max_num_batched_tokens: 2048
    max_num_seqs: 256

# Support for multi-modal training: Critic will use the same model with auto-added value head
critic:
  model:
    trust_remote_code: True

# Support for multi-modal training: Environment configuration for vision input
es_manager:
  train:
    env_groups: 1
    group_size: 4  # Smaller groups for vision training
  val:
    env_groups: 16
    group_size: 1

custom_envs:
  SimpleSokoban:
    env_type: "sokoban"
    max_actions_per_traj: 8  # Slightly reduced for vision training
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right || Right || Up</answer>."
    max_tokens: 128
    max_turn: 5
    env_config:
      dim_x: 5  # Slightly smaller for vision training
      dim_y: 5
      num_boxes: 1
      max_steps: 50
      # Support for multi-modal training: Use rgb_array for vision input
      render_mode: "rgb_array"

# Support for multi-modal training: Training-specific settings for vision models
trainer:
  project_name: lmgame_multimodal
  experiment_name: sokoban_vision
  total_training_steps: 100
  validation_steps: 1
  val_before_train: True
  test_freq: 20  # More frequent validation for vision training 