custom_envs:

  SimpleSokoban:
    env_type: sokoban
    max_actions_per_traj: 10 # used in environment state manager to control the actual max actions executed per trajectory
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right || Right || Up</answer>."
    max_tokens: 100 # used to curate llm prompt "max words", not used for rollout
    max_turn: 5
    env_config: 
      dim_room: [6, 6]
      num_boxes: 1
      max_steps: 100
      search_depth: 300
      grid_lookup: {0: "#", 1: "_", 2: "O", 3: "√", 4: "X", 5: "P", 6: "S"}
      grid_vocab: {"#": "wall", "_": "empty", "O": "target", "√": "box on target", "X": "box", "P": "player", "S": "player on target"}
      action_lookup: {1: "Up", 2: "Down", 3: "Left", 4: "Right"}
      render_mode: "text"
 
  GSM8K_NoThink:
    env_type: gsm8k
    max_actions_per_traj: 1
    env_instruction: "You are solving Math problems. Let's think step by step. Always put the answer in integer at the end of your response. "
    max_tokens: 100
    max_turn: 1
    env_config: 
      max_steps: 5
      split: "train"

  GSM8K_NoThink_Turn_5:
    env_type: gsm8k
    max_actions_per_traj: 5
    env_instruction: "You are solving Math problems. Let's think step by step. Always put the answer in integer at the end of your response. "
    max_tokens: 100
    max_turn: 5
    env_config: 
      max_steps: 5
      split: "train"

  GSM8K:
    env_type: gsm8k
    max_actions_per_traj: 1
    env_instruction: "You are solving Math problems. Let's think step by step. You should put all thinking process into <think>...</think> and then only give the final answer in <answer>...</answer>."
    max_tokens: 100
    max_turn: 1
    env_config: 
      max_steps: 5
      split: "train"

  GSM8K_Turn_5:
    env_type: gsm8k
    max_actions_per_traj: 5
    env_instruction: "You are solving Math problems. Let's think step by step. You should put all thinking process into <think>...</think> and then only give the final answer in <answer>...</answer>."
    max_tokens: 100
    max_turn: 5
    env_config: 
      max_steps: 5
      split: "train"

  Blocksworld3_Sparse:
    env_type: blocksworld
    max_actions_per_traj: 20
    max_turn: 10
    env_instruction: "You are solving Blocksworld problems. Each state is represented by a graphical stack of blocks. There are 3 blocks: block 1, block 2, and block 3. You can only move a block if there is no other block on top of it. Each action should be formatted as:\"move X to Y\", where X is the block number you're moving, and Y is either 0, meaning move the block to the table; or another block number, meaning move it on top of that block.\n\nA state is like this:\n _ \n|2|\n ¯ \n _  _ \n|1||3|\n ¯  ¯ \nThis means: Block 2 is on top of block 1, and Block 1, 3 is on the table. Another example:\n _ \n|1|\n ¯ \n _ \n|3|\n ¯ \n _ \n|2|\n ¯ \nThis means: Block 1 is on top of block 3, Block 3 is on top of block 2, and Block 2 is on the table. \nYou are given the current state and the goal state, and you need to find a sequence of actions to move the blocks to the goal state. The answer should be a sequence of actions, like <answer>(move 2 to 0) || (move 1 to 2)</answer>" 
    max_tokens: 100
    env_config:
      num_blocks: 3
      max_steps: 100
      render_mode: '2d_sparse'

  Blocksworld3_1D:
    env_type: blocksworld
    max_actions_per_traj: 20
    max_turn: 10
    env_instruction: "You are solving blocksworld problems. There are 3 blocks on the table. The state is represented by an array of 3 numbers, each number shows what the block is on. A value of 0 means the block is on the table. A value of 1, 2 or 3 means the block is on top of that block. For example, if the current state is [2, 0, 1], then block 1 is on top of Block 2, Block 2 is on the table, and Block 3 is on top of Block 1. Each action should be formatted as:\"move X to Y\", where X is the block number you're moving, and Y is either 0, meaning move the block to the table; or another block number, meaning move it on top of that block. You can only move a block if there is no other block on top of it. You are given the current state and the goal state, and you need to find a sequence of actions to move the blocks to the goal state. The answer should be a sequence of actions, like <answer>(move 2 to 0) || (move 1 to 2)</answer>"
    max_tokens: 100
    env_config:
      num_blocks: 3
      max_steps: 100
      render_mode: '1d'

  Blocksworld3_Text:
    env_type: blocksworld
    max_actions_per_traj: 20
    max_turn: 10
    env_instruction: "You are solving blocksworld problems. There are 3 blocks: block 1, block 2, and block 3. You can only move a block if there is no other block on top of it. Each action should be formatted as:\"move X to Y\", where X is the block number you're moving, and Y is either 0, meaning move the block to the table; or another block number, meaning move it on top of that block. You are given the current state and the goal state, and you need to find a sequence of actions to move the blocks to the goal state. The answer should be a sequence of actions, like <answer>(move 2 to 0) || (move 1 to 2)</answer>"
    max_tokens: 100
    env_config:
      num_blocks: 3
      max_steps: 100
      render_mode: 'text'

  Bird:
    env_type: bird
    max_actions_per_traj: 1
    max_turn: 1
    env_instruction: "Translate the question into SQL given database information. Replay with one fenced block that contains only SQL code:\n```sql\n...\n``\n."
    max_tokens: 1024
    env_config:
      max_steps: 5

  Tetris_1:
    env_type: tetris
    max_actions_per_traj: 40
    max_turn: 20
    env_instruction: "You are solving a simplified version of Tetris puzzle. The game board is a 4*4 grid, and blocks fall one at a time from the top. There is only one type of block, that is 1×1 square marked in X. Your goal is to fill the last row completely with blocks to get points, with the state such as \n____\n____\n____\n####\nYou can only move the current block left, right, or down. The answer should be a sequence of actions, like <answer>Left || Right || Down</answer> Hint: If we see empty space (_) in the last row, try to left/right move the current block to let it drop down to the empty space."
    max_tokens: 100
    env_config:
      dim_x: 4
      dim_y: 4
      max_steps: 100
      box_type: 1

  Tetris_2:
    env_type: tetris
    max_actions_per_traj: 40
    max_turn: 20
    env_instruction: "You are solving a simplified version of Tetris puzzle. The game board is a 4*4 grid, and blocks fall one at a time from the top. Your goal is to fill the last row completely with blocks to get points, with the state such as \n____\n____\n____\n####\n. You can only move the current block left, right, or down. The answer should be a sequence of actions, like <answer>Left || Right || Down</answer> Hint: If we see empty space (_) in the last row, try to left/right move the current block to let it drop down to the empty space."
    max_tokens: 100
    env_config:
      dim_x: 4
      dim_y: 4
      max_steps: 100
      box_type: 2

  LargerSokoban_Dim_8:
    env_type: sokoban
    max_actions_per_traj: 10
    env_instruction: "You are solving the Sokoban puzzle. You are the player and you need to push all boxes to targets. When you are right next to a box, you can push it by moving in the same direction. You cannot push a box through a wall, and you cannot pull a box. The answer should be a sequence of actions, like <answer>Right || Right || Up</answer>"
    max_tokens: 100
    max_turn: 5
    env_config:
      dim_x: 8
      dim_y: 8
      num_boxes: 1
      max_steps: 100
      search_depth: 30
      action_lookup: {1: "Up", 2: "Down", 3: "Left", 4: "Right"}

  WebShop:
    env_type: webshop
    max_actions_per_traj: 30
    max_turn: 10
    env_instruction: "You are browsing an online shop. Based on the instruction, find the product that matches the production description. You need to iteratively take action, read the website and decide what action to take next until finding the product. Available actions depends on the page: in the search page you can search keywords, in the search result page you can click an item url or click[next >] to navigate to next page, in the product page you can click[description] or click[features] to see the details, click[blue] or click[x-large] to choose size and colors, click[buy now] when you decided to buy the product, click[back to search] to return to search page. Example process: I need a gingko light and 20x20 pillow cover that is hand painted. First search[gingko light 20x20 pillow cover hand painted], answer format: <answer>search[blanket with fleece throw]</answer>. Valid answer is search[<keywords>] or click[<clickable>]."
    max_tokens: 100
    env_config: null
  