defaults:
  - base
  - _self_

# Override specific values from base configuration
experiment_name: qwen_half_b_think_sokoban
validation: [simpleSokobanAgent, largeSokobanAgent, gsm8kAgent_single_turn, gsm8kAgent_5_turn, blocksworldAgent_text, blocksworldAgent_1d, blocksworldAgent_2d_sparse, tetrisAgent_type_1_dim_4, tetrisAgent_type_2_dim_3, tetrisAgent_type_2_dim_4, webshopAgent, birdAgent]
validation_agent_group_num: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
validation_agent_group_size: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

# Override rollout config to include the new validation agents
rollout:
  agent_group_num: [8]
  agent_group_size: [16] # number of agents = agent_group_num * agent_group_size
  validation_agent_group_num: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
  validation_agent_group_size: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  training: [simpleSokobanAgent]
  validation: [simpleSokobanAgent, largeSokobanAgent, gsm8kAgent_single_turn, gsm8kAgent_5_turn, blocksworldAgent_text, blocksworldAgent_1d, blocksworldAgent_2d_sparse, tetrisAgent_type_1_dim_4, tetrisAgent_type_2_dim_3, tetrisAgent_type_2_dim_4, webshopAgent, birdAgent]
  validation_seed: 123
  truncation: left  # truncate from left (oldest tokens) to keep recent context
  use_turn_scores: False  # for GAE computation
  rollout_filter_ratio: 0.25  # filter ratio for rollout selection
  rollout_filter_type: std  # std or std_rev for filtering criteria
  reward_normalization:
    grouping: "state" # state / batch / inductive
    method: "identity" # asym_clip / identity / mean_std