game_env:
  name: "nineteen_forty_two"
  description: "1942 flight shooting game environment"
  env_type: "custom"
  render_mode: "human"
  max_steps: 5000
  seed: 42
  num_runs: 1

agent:
  # Global agent settings
  name: "1942_nes_agent"
  model_name: "claude-3-7-sonnet-latest"
  cache_dir: "cache/nineteen_forty_two"
  reasoning_effort: "high"
  token_limit: 100000
  harness: false  # Whether to use the perception-memory-reasoning pipeline
  observation_mode: "both"
  use_reflection: true
  # Module-specific settings
  modules:
    base_module:
    
    perception_module:
      observation_mode: "both"  # Options: "vision", "text", "both"

    memory_module:
    
    reasoning_module:
      use_perception: True
      use_memory: True
      use_cot: True
